image : mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - code_quality

build:
  stage: build
  tags:
    - docker
  script:
    - dotnet build
  only:
    - /^feature\/.+$/
    - develop
    - master

code_quality:
  stage: code_quality
  tags:
    - docker
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
      - "apt-get update"
      - "apt-get install --yes openjdk-11-jre"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - dotnet sonarscanner begin  /d:sonar.login=$SONAR_TOKEN /d:sonar.host.url="$SONAR_URL" /n:"${SONAR_PROJECT_NAME}" /k:"$SONAR_PROJECT_KEY" /d:sonar.branch.name="$CI_COMMIT_BRANCH"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}
  
  allow_failure: true
  only:
    - /^feature\/.+$/
    - develop
    - master

